[build]
  command = "npm --prefix resume-app ci && npm --prefix resume-app run build"
  publish = "resume-app/dist/resume-app/browser"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
